image: python:3.10

pages:
  script:
    # 1. Instalacja zależności
    - pip install -r requirements.txt

    # 2. (Opcjonalnie) ustawiamy zmienną środowiskową GITLAB_TOKEN,
    #    jeżeli jest dodana w Settings -> CI/CD -> Variables
    #    - export GITLAB_TOKEN="$GITLAB_TOKEN"

    # 3. Generowanie plików HTML
    - python generate_portfolio.py

    # 4. Tworzymy folder public/ i kopiujemy do niego pliki,
    #    które mają być dostępne jako strony
    - mkdir public
    - cp -r *.html public/
    - cp -r static/ public/static/

  artifacts:
    paths:
      - public
    expire_in: 1 week

  only:
    - main  # pipeline ruszy tylko przy pushu na main
