image: python:3.10

stages:
  - build

pages:
  stage: build
  script:
    # 1. Instalacja zależności
    - pip install -r requirements.txt

    # 2. Generowanie plików HTML
    - python generate_portfolio.py

    # 3. Tworzenie folderu public i kopiowanie wszystkich plików
    - mkdir public
    - cp -r *.html public/
    - cp -r static/ public/static/

  artifacts:
    paths:
      - public
    expire_in: 1 week

  only:
    - main  # pipeline ruszy tylko przy pushu na main

  schedule:
    - cron: "0 0 * * *" # Uruchomienie codziennie o północy UTC
      ref: main
