image: python:3.10

pages:
  script:
    # 1. Instalacja zależności
    - pip install -r requirements.txt

    # 2. Generowanie plików HTML
    - python generate_portfolio.py

    # 3. Tworzenie folderu public i kopiowanie wszystkich plików
    - mkdir public
    - cp -r *.html public/
    - cp -r static/ public/static/
    - cp -r templates/ public/templates/ # Jeśli szablony są potrzebne

  artifacts:
    paths:
      - public
    expire_in: 1 week

  only:
    - main  # pipeline ruszy tylko przy pushu na main

